site_name: PHP Chess
pages:
  - Home: index.md
  - Getting Started: getting-started.md
  - Read PGN: read-pgn.md
  - Read LAN: read-lan.md
  - Convert FEN to Board: convert-fen-to-board.md
  - Play Computer: play-computer.md
theme: readthedocs
