site_name: PHP Chess
pages:
  - Home: index.md
  - Chess\Game: game.md
  - Chess\Grandmaster: grandmaster.md
  - Chess\Heuristics: heuristics.md
  - Chess\Movetext: movetext.md
  - Chess\Player: player.md
  - Chess\Array\AsciiArray: array-ascii-array.md
  - Chess\Array\PieceArray: array-piece-array.md
  - Chess\FEN\BoardToStr: fen-board-to-str.md
  - Chess\FEN\ShortStrToPgn: fen-short-str-to-pgn.md
  - Chess\FEN\StrToBoard: fen-str-to-board.md
  - Chess\FEN\StrToPgn: fen-str-to-pgn.md
  - Chess\Media\BoardToMp4: media-board-to-mp4.md
  - Chess\Media\BoardToPng: media-board-to-png.md
  - Chess\UciEngine\Stockfish: uciengine-stockfish.md
  - Chess\Variant\Classical\Board: variant-classical-board.md
  - Chess\Variant\Classical\Randomizer\Checkmate\TwoBishopsRandomizer: variant-classical-randomizer-checkmate-two-bishops-randomizer.md
  - Chess\Variant\Classical\Randomizer\Endgame\PawnEndgameRandomizer: variant-classical-randomizer-endgame-pawn-endgame-randomizer.md
  - Chess\Variant\Classical\Randomizer\Randomizer: variant-classical-randomizer-randomizer.md
  - Command Line Interface: cli.md
  - Usage: usage.md
theme: readthedocs
