site_name: PHP Chess
pages:
  - Home: index.md
  - Installation: installation.md
  - Getting Started: getting-started.md
  - Read PGN: read-pgn.md
  - Read LAN: read-lan.md
  - Convert FEN to Board: convert-fen-to-board.md
  - Convert Board to PNG Image: convert-board-to-png-image.md
  - Convert Board to MP4: convert-board-to-mp4.md
  - Play Like a Pro: play-like-a-pro.md
  - Play Computer: play-computer.md
  - Heuristics: heuristics.md
theme: readthedocs
